# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ddef9e5ad4133418acc5fba309b0fa74"
name = "learn-extentions"
handle = "learn-extentions"
application_url = "https://learn-extentions.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products,write_themes,read_themes"

[auth]
redirect_urls = [
  "https://learn-extentions.onrender.com/auth/callback",
  "https://learn-extentions.onrender.com/auth/shopify/callback",
  "https://learn-extentions.onrender.com/api/auth/callback"
]

[pos]
embedded = false